name: Build and deploy Docker to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: annazar7/azure-voice-assistant:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9DA1EF0AF254980B4AB1D57F0E3BDB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F82C943AABA5454191D3F2BA2F8194C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2AFA2EC302534587925239EAA6F2CEF2 }}

      - name: Restart Azure Web App (pull new image)
        run: |
          az webapp restart --name Azure-Voice-Assistant --resource-group merito1801